### ISSUE TITLE
Add License Information

### ISSUE THREAD

**Issue by thenanobel** [alireza6677/clear-notifs-gnome-ext#1]
Hello,

It's good to see that you are sharing the source code of **Clear All Notifications**. I guess, you shared the source code of this software so that anyone can run, copy, distribute, study, change and improve the software. In other words, you want your software to respect the users' freedom, what any [free software](https://www.gnu.org/philosophy/free-sw.html) does.

Unfortunately, you haven't added any license information to the source code of this program. As long as, there is [**NO LICENSE**](https://www.gnu.org/licenses/license-list.html#NoLicense) with the source code, we cannot consider a software as a free software, even if you have no problem to let anyone have the freedom to run, copy, distribute, study, change and improve the software.

I wish, you want your software to respect the freedom of its users, and have no problem to license it under a free software license, for example, the [GNU General Public License](https://www.gnu.org/licenses/licenses.html#GPL).

Thanks.

Nave Nobel

**Comment by TheWeirdDev** [comment]
I added GPL3.
Thank you.

**Comment by thenanobel** [comment]
Thank you too!
